# Generated by Django 4.1.4 on 2023-02-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='vacunado',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
